spring.datasource.url=jdbc:postgresql://88.99.189.55:5432/crudcloud_db
spring.datasource.username=crudzaso_user
spring.datasource.password=crudzaso123!
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false 
spring.jpa.properties.hibernate.default_batch_fetch_size=10
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=crudcloud22@gmail.com
spring.mail.password=rtpbsaodwaolwmgi
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

crudcloud.public.host=api.cold-brew.crudzaso.com 

shared.container.mysql[0].container-id=crudcloud_pool_mysql
shared.container.mysql[0].host=mysql-pool
shared.container.mysql[0].port=3306
shared.container.mysql[0].admin-user=root
shared.container.mysql[0].admin-password=MyS3cR3t_1995_Db!

shared.container.postgresql[0].container-id=crudcloud_pool_postgres
shared.container.postgresql[0].host=postgres-pool
shared.container.postgresql[0].port=5432
shared.container.postgresql[0].admin-user=crudcloud_admin
shared.container.postgresql[0].admin-password=P0st_Gr3S_S3rv3r_Pwd#

shared.container.mongodb[0].container-id=crudcloud_pool_mongodb
shared.container.mongodb[0].host=mongodb-pool
shared.container.mongodb[0].port=27017
shared.container.mongodb[0].admin-user=crudcloud_admin
shared.container.mongodb[0].admin-password=M0nGoDb_R00t_Acc3ss!

shared.container.redis[0].container-id=crudcloud_pool_redis
shared.container.redis[0].host=redis-pool
shared.container.redis[0].port=6379
shared.container.redis[0].admin-user=default
shared.container.redis[0].admin-password=R3d1s_C4chE_7!

shared.container.cassandra[0].container-id=crudcloud_pool_cassandra
shared.container.cassandra[0].host=cassandra-pool
shared.container.cassandra[0].port=9042
shared.container.cassandra[0].admin-user=cassandra_admin
shared.container.cassandra[0].admin-password=Ca55andR4_Key!

shared.container.sqlserver[0].container-id=crudcloud_pool_sqlserver
shared.container.sqlserver[0].host=sqlserver-pool
shared.container.sqlserver[0].port=1433
shared.container.sqlserver[0].admin-user=SA
shared.container.sqlserver[0].admin-password=SQLSvr_2024!